git+docker improvements
version, build branch

diff --git a/docker/run/Dockerfile b/docker/run/Dockerfile
--- a/docker/run/Dockerfile
+++ b/docker/run/Dockerfile
@@ -1,12 +1,14 @@
 # Use the latest slim version of Debian
 FROM debian:bookworm-slim
 
+# Check if the argument is provided, else throw an error
+ARG BRANCH
+RUN if [ -z "$BRANCH" ]; then echo "ERROR: BRANCH is not set!" >&2; exit 1; fi
+
 # Update and install necessary packages
 RUN apt-get update && apt-get install -y \
     python3 \
     python3-pip \
-    python3-dev \
-    python3-babel \
     python3-venv \
     nodejs \
     npm \
@@ -15,12 +17,7 @@ RUN apt-get update && apt-get install -y \
     curl \
     wget \
     git \
-    build-essential \
     ffmpeg 
-
-# Cleanup package list
-RUN rm -rf /var/lib/apt/lists/*
-RUN apt-get clean
 
 # Set up SSH
 RUN mkdir /var/run/sshd && \
@@ -33,12 +30,16 @@ COPY ./fs/ /
 # install additional software
 RUN bash /ins/install_searxng.sh
 
-# install a0 with caching
-RUN bash /ins/install_A0.sh
+# install A0
+RUN bash /ins/install_A0.sh $BRANCH
 
-# cleanup repo and install a0 without caching, this speeds up builds
-ARG CACHE_DATE=unknown
-RUN echo "cache buster $CACHE_DATE" && bash /ins/install_A02.sh
+# cleanup repo and install A0 without caching, this speeds up builds
+ARG CACHE_DATE=none
+RUN echo "cache buster $CACHE_DATE" && bash /ins/install_A02.sh $BRANCH
+
+# Cleanup package list
+RUN rm -rf /var/lib/apt/lists/*
+RUN apt-get clean
 
 # Expose ports
 # EXPOSE 22
